<h2><? echo($texts["faq_headline"]); ?></h2>
<h3><? echo($texts["faq_question_1"]); ?></h3>
<p><? echo($texts["faq_answer_1"]); ?></p>
<h3><? echo($texts["faq_question_2"]); ?></h3>
<p><? echo($texts["faq_answer_2"]); ?></p>
<h3><? echo($texts["faq_question_3"]); ?></h3>
<p><? echo($texts["faq_answer_3"]); ?></p>
<h3><? echo($texts["faq_question_4"]); ?></h3>
<p><? echo($texts["faq_answer_4"]); ?></p>
<h3><? echo($texts["faq_question_5"]); ?></h3>
<p><? echo($texts["faq_answer_5"]); ?></p>
<h3><? echo($texts["faq_question_6"]); ?></h3>
<p><? echo($texts["faq_answer_6"]); ?></p>